#!/bin/bash

# Install nginx
apt-get update -y
apt-get install nginx -y

# Create custom 404 page
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html

# Configure Nginx to use custom 404 page
cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}
EOF

# Restart Nginx
kill -HUP $(pgrep -f nginx)
